apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-website
  namespace: default        # <- Added namespace
  labels:
    app: college
spec:
  replicas: 2
  selector:
    matchLabels:
      app: college 
  template:
    metadata:
      labels:
        app: college
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
  
