apiVersion: v1
kind: Service
metadata:
  name: college-websitea
  namespace: default
  labels:
    app: college
spec:
  type: ClusterIP
  selector:
    app: college
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
