FROM nginx:alpine

COPY appbox/suresh/index.html usr/share/nginx/html/index.html
COPY appbox/suresh/style.css usr/share/nginx/html/style.css
COPY appbox/suresh/script.js usr/share/nginx/html/script.js

EXPOSE 80
