apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-app
  labels:
    app: doctor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-app
  template:
    metadata:
      labels:
        app: doctor-app
    spec:
      containers:
      - name: doctor-app
        image: suresh2dev2/doctorapp/doctor-app:latest   # replace with your image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  selector:
    app: doctor-app
  type: NodePort   # Use ClusterIP for minikube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30202
