apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-app
  labels:
    app: doctor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-app
  template:
    metadata:
      labels:
        app: doctor-app
    spec:
      containers:
      - name: doctor-app
        image: suresh2dev2/doctorapp:latest  # replace with your image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  selector:
    app: doctor-app
  type: NodePort   # For external access in most clusters
  ports:
  - protocol: TCP
    port: 8080         # External service port
    targetPort: 80     # Container port inside the pod
    nodePort: 30007    # Optional: specify NodePort (30000–32767 range)
