apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer-app
  labels:
    app: summer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summer-app
  template:
    metadata:
      labels:
        app: summer-app
    spec:
      containers:
      - name: summer-app
        image: suresh2dev2/summer-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: summer-app-service
spec:
  selector:
    app: summer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
