apiVersion: apps/v1
kind: Deployment
metadata:
  name: realme-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realme-app
  template:
    metadata:
      labels:
        app: realme-app
    spec:
      containers:
      - name: realme-app
        image: suresh2dev2/realme-app:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: realme-service
spec:
  type: NodePort
  selector:
    app: realme-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
