name: Build & Deploy Water Reminder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/water-reminder:latest appbox/drinkingwater

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/water-reminder:latest

    - name: Set Kubernetes Config
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f appbox/drinkingwater/k8s/k8s-deployment.yaml  --validate=false
        kubectl get pods
