
name: Install Jenkins with Helm

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

defaults:
  run:
    shell: "C:\\Program Files\\Git\\bin\\bash.exe"  # ✅ force Git Bash on Windows runner

jobs:
  install-jenkins:
    runs-on: self-hosted   # or ubuntu-latest if cluster access configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Jenkins via Helm
        run: |
          helm upgrade --install jenkins jenkinsci/jenkins \
           --namespace jenkins \
           --set controller.serviceType=NodePort \
           --set controller.nodePort=30090 \
           --set persistence.enabled=true \
           --set persistence.size=1Gi \
           --set controller.resources.requests.cpu=200m \
           --set controller.resources.requests.memory=254Mi \
           --set controller.resources.limits.cpu=300m \
           --set controller.resources.limits.memory=300mi

      - name: Wait for Jenkins Pod to be Ready
        run: |
          kubectl rollout status deployment/jenkins --namespace=jenkins --timeout=300s

      - name: Get Jenkins Admin Password
        run: |
          echo "Admin password:"
          kubectl get secret --namespace jenkins jenkins \
            -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode
          echo
