name: Install Jenkins with Helm

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh  # Use PowerShell on Windows runner

jobs:
  install-jenkins:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

   

      - name: Create namespace for Jenkins
        run: |
          kubectl create namespace jenkins -ErrorAction SilentlyContinue

      - name: Install Jenkins via Helm
        run: |
          helm upgrade --install jenkins jenkinsci/jenkins `
            --namespace jenkins `
            --set controller.serviceType=NodePort `
            --set controller.nodePort=30090 `
            --set persistence.enabled=true `
            --set persistence.size=200Mi `
            --set controller.resources.requests.cpu=150m `
            --set controller.resources.requests.memory=256Mi `
            --set controller.resources.limits.cpu=300m `
            --set controller.resources.limits.memory=300Mi

      - name: Wait for Jenkins Pod to be Read
        run: |
          kubectl rollout status deployment/jenkins --namespace=jenkins --timeout=300s

      - name: Get Jenkins Admin Password
        run: |
          Write-Host "Admin password:"
          kubectl get secret --namespace jenkins jenkins `
            -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode
          Write-Host ""
