name: Deploy Jenkins with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # your Windows self-hosted runner

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3



      # Step 3: Add Jenkins Helm repo
      - name: Add Jenkins Helm repo
        shell: pwsh
        run: |
          & "C:\Program Files\helm\helm.exe" repo add jenkinsci https://charts.jenkins.io

      # Step 4: Update Helm repos
      - name: Update Helm repos
        shell: pwsh
        run: |
          & "C:\Program Files\helm\helm.exe" repo update

      # Step 5: Deploy/Upgrade Jenkins
      - name: Deploy Jenkins
        shell: pwsh
        run: |
          & "C:\Program Files\helm\helm.exe" upgrade --install jenkins jenkinsci/jenkins `
            --namespace jenkins `
            --create-namespace `
            --set controller.serviceType=NodePort `
            --set controller.nodePort=30090 `
            --set persistence.enabled=true `
            --set persistence.size=200Mi `
            --set controller.resources.requests.cpu=200m `
            --set controller.resources.requests.memory=300Mi `
            --set controller.resources.limits.cpu=300m `
            --set controller.resources.limits.memory=400Mi
