# name: new deployment01
# on:
#   workflow_dispatch:   # manual trigger
#   push:
#     branches: ["main"]

# jobs:
#   deploy:
#     runs-on: self-hosted   # your local laptop runner
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Deploy StudentApp to Kubernetes
#         run: |
#           kubectl apply -f appbox/maihi-demo
#           # kubectl rollout status deployment/student-app
#       - name: Validate my deployemnts 
#         run: |
#           kubectl get deployment student-app
