name: Prometheus & Grafana

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # Set Default StorageClass
      # -----------------------------
      - name: Set Default StorageClass
        shell: powershell
        run: |
          kubectl patch storageclass local-path --type=merge -p `
          '{\"metadata\": {\"annotations\": {\"storageclass.kubernetes.io/is-default-class\": \"true\"}}}'

      # -----------------------------
      # Add Helm Repos
      # -----------------------------
      - name: Add Helm Repos
        shell: powershell
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      # -----------------------------
      # Create Prometheus values
      # -----------------------------
      - name: Create prometheus-values.yaml
        shell: powershell
        run: |
          @"
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

server:
  service:
    type: NodePort
    nodePort: 32001
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: "local-path"

alertmanager:
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
"@ | Out-File -FilePath prometheus-values.yaml -Encoding utf8

      - name: Install Prometheus
        shell: powershell
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus -f prometheus-values.yaml

      # -----------------------------
      # Create Grafana values
      # -----------------------------
      - name: Create grafana-values.yaml
        shell: powershell
        run: |
          @"
resources:
  limits:
    cpu: 150m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

service:
  type: NodePort
  nodePort: 32000

persistence:
  enabled: true
  size: 2Gi
  storageClassName: "local-path"
"@ | Out-File -FilePath grafana-values.yaml -Encoding utf8

      - name: Install Grafana
        shell: powershell
        run: |
          helm upgrade --install grafana grafana/grafana -f grafana-values.yaml

      # -----------------------------
      # Get Grafana Admin Password
      # -----------------------------
      - name: Get Grafana Admin Password
        shell: powershell
        run: |
          $encoded = kubectl get secret grafana -o jsonpath="{.data.admin-password}"
          $bytes = [System.Convert]::FromBase64String($encoded)
          $decoded = [System.Text.Encoding]::UTF8.GetString($bytes)
          Write-Host "Grafana Admin Password: $decoded"
