name: Deploy Single Pod to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create Nginx Pod
        run: |
          kubectl run nginx-pod --image=nginx:latest

      - name: Create NodePort Service
        run: |
          kubectl expose pod nginx-pod1 \
            --name=nginx-service \
            --port=80 \
            --target-port=80 \
            --type=NodePort

      - name: Verify Deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc nginx-service -o wide
