name: CI-CD Pipeline

on:
workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-website ./website

      - name: Run Container
        run: |
          docker run -d -p 8080:80 --name website my-website
          sleep 5
          curl http://localhost:8080
